/**
 * Repositorio de Libros Curados - Solo libros gratuitos de Project Gutenberg.
 * Capa de Infraestructura.
 * 
 * TODOS los libros están verificados en Project Gutenberg.
 * Portadas: https://www.gutenberg.org/cache/epub/{ID}/pg{ID}.cover.medium.jpg
 * Descarga: https://www.gutenberg.org/ebooks/{ID} (página con múltiples formatos)
 * Lectura online: https://www.gutenberg.org/ebooks/{ID}.html.images (HTML directo)
 */

import { Book } from '../../domain/entities/Book';
import { ReaderProfile } from '../../domain/entities/ReaderProfile';
import { BookRepository } from '../../application/ports/BookRepository';

/** Genera URL de portada desde Project Gutenberg */
function pgCover(id: number): string {
  return `https://www.gutenberg.org/cache/epub/${id}/pg${id}.cover.medium.jpg`;
}

/** Genera URL de la página de descarga en Project Gutenberg */
function pgDownload(id: number): string {
  return `https://www.gutenberg.org/ebooks/${id}`;
}

/** Genera URL de lectura online en Project Gutenberg */
function pgRead(id: number): string {
  return `https://www.gutenberg.org/ebooks/${id}.html.images`;
}

const curatedDatabase: Book[] = [
  // === LIBROS EN ESPAÑOL (verificados en Gutenberg) ===
  {
    id: 'pg-2000',
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    description: 'Las aventuras del ingenioso hidalgo Don Quijote y su fiel escudero Sancho Panza recorriendo España en busca de hazañas caballerescas. La novela más importante de la literatura en español.',
    coverUrl: pgCover(2000),
    pageCount: 400,
    rating: 4.8,
    publishedYear: 1605,
    language: 'es',
    readingLevel: 'avanzado',
    previewLink: pgRead(2000),
    downloadLink: pgDownload(2000),
    accessType: 'libre',
    whyPerfectReasons: [
      'La obra maestra de la literatura en español',
      'Aventuras divertidas y episodios independientes',
      'Puedes leer capítulos sueltos sin perderte',
    ],
    score: 0,
    categories: ['aventura', 'clasicos', 'ficcion', 'humor'],
  },
  {
    id: 'pg-62627',
    title: 'El caso extraño del Doctor Jekyll',
    author: 'Robert Louis Stevenson',
    description: 'Un abogado de Londres investiga la extraña relación entre su viejo amigo, el Dr. Jekyll, y el misterioso Mr. Hyde. Una novela corta de misterio y terror que se lee de un tirón.',
    coverUrl: pgCover(62627),
    pageCount: 100,
    rating: 4.6,
    publishedYear: 1886,
    language: 'es',
    readingLevel: 'facil',
    previewLink: pgRead(62627),
    downloadLink: pgDownload(62627),
    accessType: 'libre',
    whyPerfectReasons: [
      'Es muy corto, se lee en una tarde',
      'El misterio te atrapa desde el primer capítulo',
      'Versión en español accesible',
    ],
    score: 0,
    categories: ['misterio', 'thriller', 'terror', 'clasicos'],
  },
  {
    id: 'pg-61851',
    title: 'Crimen y Castigo',
    author: 'Fiódor Dostoyevski',
    description: 'Un joven estudiante empobrecido en San Petersburgo comete un crimen y lucha con la culpa y la paranoia. Un thriller psicológico que explora los límites de la mente humana.',
    coverUrl: pgCover(61851),
    pageCount: 550,
    rating: 4.7,
    publishedYear: 1866,
    language: 'es',
    readingLevel: 'avanzado',
    previewLink: pgRead(61851),
    downloadLink: pgDownload(61851),
    accessType: 'libre',
    whyPerfectReasons: [
      'Thriller psicológico que engancha como una serie de TV',
      'Reflexión profunda sobre la moralidad',
      'Traducción al español disponible gratis',
    ],
    score: 0,
    categories: ['thriller', 'psicologia', 'ficcion', 'clasicos'],
  },
  {
    id: 'pg-21143',
    title: 'Las Fábulas de Esopo',
    author: 'Esopo',
    description: 'Colección de fábulas cortas con animales que hablan y enseñan lecciones de vida. Historias breves, entretenidas y llenas de sabiduría milenaria.',
    coverUrl: pgCover(21143),
    pageCount: 80,
    rating: 4.5,
    publishedYear: -600,
    language: 'es',
    readingLevel: 'facil',
    previewLink: pgRead(21143),
    downloadLink: pgDownload(21143),
    accessType: 'libre',
    whyPerfectReasons: [
      'Historias cortísimas, perfectas para empezar',
      'Cada fábula tiene una moraleja clara',
      'Puedes leer una al día en 2 minutos',
    ],
    score: 0,
    categories: ['ficcion', 'filosofia', 'clasicos', 'aventura'],
  },
  {
    id: 'pg-58221',
    title: 'La Odisea',
    author: 'Homero',
    description: 'El viaje épico de Ulises intentando regresar a casa después de la guerra de Troya. Monstruos, dioses, aventuras marítimas y un héroe que nunca se rinde.',
    coverUrl: pgCover(58221),
    pageCount: 350,
    rating: 4.7,
    publishedYear: -800,
    language: 'es',
    readingLevel: 'medio',
    previewLink: pgRead(58221),
    downloadLink: pgDownload(58221),
    accessType: 'libre',
    whyPerfectReasons: [
      'Aventuras emocionantes con monstruos y dioses',
      'Cada episodio es una historia independiente',
      'La historia de aventuras más famosa de todos los tiempos',
    ],
    score: 0,
    categories: ['aventura', 'clasicos', 'ficcion', 'fantasia'],
  },
  {
    id: 'pg-55514',
    title: 'Cuentos de amor',
    author: 'Emilia Pardo Bazán',
    description: 'Colección de cuentos breves sobre el amor en todas sus formas: pasional, prohibido, tierno y trágico. Historias cortas escritas con maestría por una de las grandes autoras españolas.',
    coverUrl: pgCover(55514),
    pageCount: 120,
    rating: 4.4,
    publishedYear: 1898,
    language: 'es',
    readingLevel: 'facil',
    previewLink: pgRead(55514),
    downloadLink: pgDownload(55514),
    accessType: 'libre',
    whyPerfectReasons: [
      'Cuentos cortísimos, ideales para leer antes de dormir',
      'Historias de amor que emocionan',
      'Cada cuento dura solo unos minutos',
    ],
    score: 0,
    categories: ['romance', 'ficcion', 'clasicos'],
  },
  {
    id: 'pg-15725',
    title: 'Doña Perfecta',
    author: 'Benito Pérez Galdós',
    description: 'Un joven ingeniero liberal llega a una ciudad española conservadora para casarse con su prima, pero el choque de ideas lo enfrenta a toda la sociedad local. Drama, tensión e intriga.',
    coverUrl: pgCover(15725),
    pageCount: 250,
    rating: 4.3,
    publishedYear: 1876,
    language: 'es',
    readingLevel: 'medio',
    previewLink: pgRead(15725),
    downloadLink: pgDownload(15725),
    accessType: 'libre',
    whyPerfectReasons: [
      'Drama con tensión que engancha como una novela moderna',
      'Lenguaje accesible del siglo XIX español',
      'Personajes con los que quieres discutir',
    ],
    score: 0,
    categories: ['ficcion', 'drama', 'clasicos', 'reflexion'],
  },
  {
    id: 'pg-57303',
    title: 'La Divina Comedia',
    author: 'Dante Alighieri',
    description: 'El viaje de Dante a través del Infierno, el Purgatorio y el Paraíso. Una travesía fantástica por mundos sobrenaturales llena de criaturas, castigos y redención.',
    coverUrl: pgCover(57303),
    pageCount: 300,
    rating: 4.8,
    publishedYear: 1320,
    language: 'es',
    readingLevel: 'avanzado',
    previewLink: pgRead(57303),
    downloadLink: pgDownload(57303),
    accessType: 'libre',
    whyPerfectReasons: [
      'Un viaje fantástico por mundos increíbles',
      'La parte del Infierno es la más entretenida',
      'Traducción al español en verso',
    ],
    score: 0,
    categories: ['fantasia', 'clasicos', 'filosofia', 'aventura'],
  },
  {
    id: 'pg-36805',
    title: 'Cuentos españoles para principiantes',
    author: 'Varios autores',
    description: 'Colección de cuentos cortos en español seleccionados especialmente para lectores que están empezando. Historias sencillas, vocabulario claro y temas universales.',
    coverUrl: pgCover(36805),
    pageCount: 100,
    rating: 4.2,
    publishedYear: 1911,
    language: 'es',
    readingLevel: 'facil',
    previewLink: pgRead(36805),
    downloadLink: pgDownload(36805),
    accessType: 'libre',
    whyPerfectReasons: [
      'Diseñado literalmente para quienes empiezan a leer',
      'Cuentos cortísimos de 2-5 páginas',
      'Vocabulario simple y claro',
    ],
    score: 0,
    categories: ['ficcion', 'aventura', 'clasicos'],
  },
  {
    id: 'pg-67092',
    title: 'El Paraíso Perdido',
    author: 'John Milton',
    description: 'La historia de la caída de Lucifer y la expulsión de Adán y Eva del Paraíso. Épica grandiosa sobre el bien, el mal y la libertad de elección.',
    coverUrl: pgCover(67092),
    pageCount: 300,
    rating: 4.5,
    publishedYear: 1667,
    language: 'es',
    readingLevel: 'avanzado',
    previewLink: pgRead(67092),
    downloadLink: pgDownload(67092),
    accessType: 'libre',
    whyPerfectReasons: [
      'Épica grandiosa con batallas entre ángeles',
      'Lucifer es uno de los personajes más fascinantes de la literatura',
      'Fundamental para entender la cultura occidental',
    ],
    score: 0,
    categories: ['fantasia', 'clasicos', 'filosofia'],
  },

  // === LIBROS EN INGLÉS (clásicos populares de Gutenberg) ===
  {
    id: 'pg-84',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    description: 'A young scientist creates a living creature from dead body parts, only to face the terrifying consequences of playing God. The original science fiction horror story.',
    coverUrl: pgCover(84),
    pageCount: 280,
    rating: 4.6,
    publishedYear: 1818,
    language: 'en',
    readingLevel: 'medio',
    previewLink: pgRead(84),
    downloadLink: pgDownload(84),
    accessType: 'libre',
    whyPerfectReasons: [
      'The original science fiction novel',
      'Shorter than you think - very readable',
      'Everyone knows the movie, but the book is way better',
    ],
    score: 0,
    categories: ['ciencia-ficcion', 'terror', 'clasicos', 'ficcion'],
  },
  {
    id: 'pg-11',
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    description: 'A young girl falls down a rabbit hole into a fantastical world of talking animals, mad tea parties, and a tyrannical Queen of Hearts. Pure imagination and fun.',
    coverUrl: pgCover(11),
    pageCount: 100,
    rating: 4.5,
    publishedYear: 1865,
    language: 'en',
    readingLevel: 'facil',
    previewLink: pgRead(11),
    downloadLink: pgDownload(11),
    accessType: 'libre',
    whyPerfectReasons: [
      'Very short and wildly entertaining',
      'Chapters are tiny and self-contained',
      'You already know the characters from the movies',
    ],
    score: 0,
    categories: ['fantasia', 'aventura', 'clasicos', 'humor'],
  },
  {
    id: 'pg-174',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    description: 'A handsome young man sells his soul so that a portrait ages instead of him. As he sinks into depravity, the painting becomes a horrifying record of his sins.',
    coverUrl: pgCover(174),
    pageCount: 254,
    rating: 4.7,
    publishedYear: 1890,
    language: 'en',
    readingLevel: 'medio',
    previewLink: pgRead(174),
    downloadLink: pgDownload(174),
    accessType: 'libre',
    whyPerfectReasons: [
      'A thriller about beauty, vanity and dark secrets',
      'Oscar Wilde\'s brilliant wit makes every page entertaining',
      'A story that feels surprisingly modern',
    ],
    score: 0,
    categories: ['terror', 'ficcion', 'clasicos', 'filosofia'],
  },
  {
    id: 'pg-345',
    title: 'Dracula',
    author: 'Bram Stoker',
    description: 'The classic tale of Count Dracula\'s attempt to move from Transylvania to England. Told through diaries and letters, this is the original vampire horror novel.',
    coverUrl: pgCover(345),
    pageCount: 418,
    rating: 4.5,
    publishedYear: 1897,
    language: 'en',
    readingLevel: 'medio',
    previewLink: pgRead(345),
    downloadLink: pgDownload(345),
    accessType: 'libre',
    whyPerfectReasons: [
      'The original vampire story, way creepier than the movies',
      'Written as diary entries, which makes it feel personal',
      'Suspense that builds perfectly',
    ],
    score: 0,
    categories: ['terror', 'misterio', 'clasicos', 'ficcion', 'suspenso'],
  },
  {
    id: 'pg-1661',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    description: 'Twelve short stories featuring the legendary detective Sherlock Holmes and his partner Dr. Watson solving mysteries in Victorian London.',
    coverUrl: pgCover(1661),
    pageCount: 220,
    rating: 4.7,
    publishedYear: 1892,
    language: 'en',
    readingLevel: 'facil',
    previewLink: pgRead(1661),
    downloadLink: pgDownload(1661),
    accessType: 'libre',
    whyPerfectReasons: [
      'Short stories - each mystery is complete and independent',
      'The world\'s most famous detective',
      'Easy, addictive reading',
    ],
    score: 0,
    categories: ['misterio', 'aventura', 'clasicos', 'ficcion', 'suspenso'],
  },
  {
    id: 'pg-64317',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'In 1920s New York, mysterious millionaire Jay Gatsby throws lavish parties trying to win back his lost love. A tale of wealth, obsession, and the American Dream.',
    coverUrl: pgCover(64317),
    pageCount: 180,
    rating: 4.5,
    publishedYear: 1925,
    language: 'en',
    readingLevel: 'facil',
    previewLink: pgRead(64317),
    downloadLink: pgDownload(64317),
    accessType: 'libre',
    whyPerfectReasons: [
      'Short, elegant, and endlessly quotable',
      'A glamorous world of parties and secrets',
      'One of the most famous novels of all time',
    ],
    score: 0,
    categories: ['ficcion', 'romance', 'clasicos', 'drama'],
  },
];

export class CuratedBooksRepository implements BookRepository {
  async searchBooks(profile: ReaderProfile, keywords: string[]): Promise<Book[]> {
    // Filtrar por idioma preferido del usuario
    return curatedDatabase.filter(book => 
      profile.language === 'cualquiera' || book.language === profile.language
    );
  }
}
